package ru.mail.ales2003.deals2017.datamodel;

public enum Attribute {
	LENGTH, WIDTH, HEIGHT, DEPTH, WEIGHT, THICKNESS, DENSITY, DIMENSIONS, SIZE, COLOR, MATERIAL, FREQUENCY, SATURATION, SENSITIVITY, SHARPNESS, GROWTH, DIAGONAL, SPEED, POWER, COOLING_POWER, HEATING_POWER, BRIGHTNESS, ENERGY_CONSUMPTION, RESISTANCE, CURRENT, VOLTAGE, PRESSURE, AGE, GENERATION

}
